name: Ship js trigger
on:
  push:
    branches:
      - master
jobs:
  build:
    if: "contains(github.event.head_commit.message, 'chore: release ')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"
      - run: |
          if [ -f "yarn.lock" ]; then
            yarn install
          else
            npm install
          fi
      - run: |
          echo "Run shipjs-trigger.yml"
          echo ${{ github.ref }}
          echo ${{ github.event_name }}
          echo ${{ github.head_ref }}
          echo ${{ github.event.head_commit.message }}
          # npm run release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
